name=multi-multigas
version=1.1.1
author=John Romkey
maintainer=John Romkey <58883+romkey@users.noreply.github.com>
sentence=Simple interface for multiple DFRobot I2C gas sensors on one bus.
paragraph=Encapsulates the DFRobot MultiGasSensor library to query specific gas sensors without managing I2C address mapping.
category=Sensors
url=https://github.com/romkey/multi-multigas
architectures=*
